local:
  vhost: "http://localhost:8000"
  wordpress_path: "/var/www/html/"
  database:
    name: "wordpress"
    user: "root"
    password: "wordpress"
    host: "database"
    charset: "utf8"
production:
  vhost: "<your_domain_name>"
  wordpress_path: "<absolute_path_to_wp_installation>" 
  database:
      name: "<db_name>"
      user: "<username>"
      password: "<password>"
      host: "localhost"
      charset: "utf8"
  ssh:
      host: "<hostname>"
      user: "<user>"
#      password: "<password>" 
# password is optional, will use public keys if available.